@startuml

abstract class AmmoTile implements Serializable, Grabbable{
    - ammos: List<Ammo>
    __
    + pickGrabbable(int, int): void
}

AmmoTile +-- AmmoTileWithAmmo
AmmoTile +-- AmmoTileWithPowerup
@enduml