@startuml
skinparam classAttributeIconSize 0
interface Observer <<Interface>>{
__
+ update(): void
}
package Controller {
class Controller implements Observer {
__
+ update(): void
}
}
Subject -> Observer
class Subject{
__
+ addObserver(Observer)
+ removeObserver(Observer)
+ notifyObserver()
}

View <- Controller
class View extends Subject implements Observer{
- model: Model
--Subject--
+ setModel(Model)
+ getModel()
--Observer--
+update()
}

Model <- View
class Model extends Subject{
}


@enduml