@startuml
skinparam classAttributeIconSize 0
package model{
    interface ModelObserver <<Interface>>{
         + onJoin(User): void
         + onLeave(User): void
         + onStart(): void
         + onUpdate(Update): void
    }
    class ModelUML <@see>
}
package view{
     interface View extends ModelObserver
     class ViewClient implements View
     class ViewGui implements View
}

package network{
    interface ClientHandler extends ModelObserver
    class SocketClientHandler implements ClientHandler
    class RMIClientHandler implements ClientHandler
}

package controller{
    class TimerController implements ModelObserver
}
@enduml